spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_system?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
